lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug BlogWeb.Plug.SetUser
  end

  scope "/", BlogWeb do
    pipe_through :browser
    resources "/posts", PostController
    get "/", PageController, :index
  end

  scope "/auth", BlogWeb do
    pipe_through :browser

    get "/logout", AuthController, :logout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # if Mix.env() in [:dev, :test] do
  #   import Phoenix.LiveDashboard.Router

  #   scope "/" do
  #     pipe_through :browser
  #     live_dashboard "/dashboard", metrics: BlogWeb.Telemetry
  #   end
  # end
end

lib/blog_web/views/shared_view.ex
defmodule BlogWeb.SharedView do
  use BlogWeb, :view
end

lib/blog_web/templates/shared/_links.html.eex
  <%= if @conn.assigns[:user] do %>
  <li><a href="#">Bem vindo! <%= @conn.assigns[:user].email %></a></li>
  <li>
    <%= link "Posts", to: Routes.post_path(@conn, :index) %>
  </li>
    <li>
    <%= link "Logout", to: Routes.auth_path(@conn, :logout) %>
  </li>
  <% else %>
  <li>
    <%= link "Logar", to: Routes.auth_path(@conn, :request, "google") %>
  </li>
<% end %>

lib/blog_web/templates/shared/_menu.html.eex
<nav>
  <div class="nav-wrapper">
    <a href="#!" class="brand-logo">Logo</a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <%= render  BlogWeb.SharedView, "_links.html", assigns %>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <%= render  BlogWeb.SharedView, "_links.html", assigns %>
</ul>